apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep-persistent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes: # Define volume
        - name: shared-counter-file
          persistentVolumeClaim:
            claimName: counter-file-claim
      containers:
        - name: pingpong
          image: melinadevops/pingpong:latest
          env:
            - name: PORT
              value: "9000"
          volumeMounts:
            - name: shared-counter-file
              mountPath: /usr/src/app/files