apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput-dep-persistent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes: # Define volume
        - name: shared-counter-file
          persistentVolumeClaim:
            claimName: counter-file-claim
      containers:
        - name: logoutput
          image: melinadevops/log_output:v2
          env:
            - name: PORT
              value: "3000"
          volumeMounts:
            - name: shared-counter-file
              mountPath: /usr/src/app/files