# Build stage
FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY . .

RUN go build -o server server.go

# Runtime stage
FROM scratch

WORKDIR /

COPY --from=builder /app/server /server

ENV PORT=3000

EXPOSE 3000

ENTRYPOINT ["./server"]