apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
data:
  PORT: "8000"
  TODO_BACKEND_URL: "http://todo-backend-svc:2428"
  STORED_IMAGES_PATH: "/usr/src/app/images/"
  IMAGE_URL: "https://picsum.photos/1200"
  IMAGE_CACHE_DURATION: "10m"