apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      namespace: project
      labels:
        app: todo-app
    spec:
      volumes: # Define volume
        - name: images
          persistentVolumeClaim:
            claimName: images-claim
      containers:
        - name: todo-app
          image: melinadevops/todo-app
          envFrom:
            - configMapRef:
                name: todo-app-config
          volumeMounts:
            - name: images
              mountPath: /usr/src/app/images