apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput-dep-persistent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes: # Define volume
        - name: shared-logfile
          persistentVolumeClaim:
            claimName: logfile-claim
      containers:
        - name: logoutput
          image: melinadevops/log_output
          volumeMounts:
            - name: shared-logfile
              mountPath: /usr/src/app/files
        - name: logserver
          image: melinadevops/logserver
          volumeMounts:
            - name: shared-logfile
              mountPath: /usr/src/app/files